server:
  port: 443
eureka:
  instance:
    hostname: service1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
      
spring:
  application:
    name: eureka-service
  datasource:
    min-idle: 5
    minIdle: 5
    validationQuery: SELECT 1 FROM DUAL
    initialSize: 5
    maxWait: 60000
    filters: stat,wall,log4j
    logSlowSql: true
    max-wait: 10000
    url: jdbc:mysql://127.0.0.1:3306/miniprogram?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    max-idle: 10
    username: root
    password: root
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    initial-size: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 20
    
    
mybatis:
  type-aliases-package:com.wpf.eurekaclient.mapper
  mapper-locations:classpath*:/mappers/*Mapper.xml
  
logging:
  file: logs/spring-boot-logging.log
